# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.


[[main]]
  name = "博客"
  url = "post/"
  weight = 20



#[[main]]
 # name = "学习笔记"
  #url = "courses/"
  #weight = 50


[[main]]
  name = "相册"
  url = "#gallery"
  weight = 70


[[main]]
  name = "关于"
  url = "#about"
  weight = 80



#[[main]]
  #name = "Demo"
 # url = "#hero"
#  weight = 10

#[[main]]
 # name = "项目"
  #url = "#projects"
  #weight = 30

#[[main]]
 # name = "刊物"
  #url = "#featured"
  #weight = 40
#[[main]]
#  name = "和我联系"
#  url = "#contact"
 # weight = 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
